#!/bin/sh /etc/rc.common
START=91
USE_PROCD=1

PROG=/usr/sbin/ECM_DEMO_AUTO

start_service(){
    config_load system
    procd_open_instance
    procd_set_param command /usr/sbin/ECM_DEMO_AUTO
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-100}
    procd_close_instance
}
