#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	pcidevid=$(cat /sys/devices/platform/soc/d0070000.pcie/pci0000:00/0000:00:00.0/device)
	pcivenid=$(cat /sys/devices/platform/soc/d0070000.pcie/pci0000:00/0000:00:00.0/vendor)
	if [ "$pcidevid" = "0x003e" -a "$pcivenid" = "0x168c" ];then
	    sleep 1
	    insmod /lib/firmware/qca6174/wlan.ko
	fi

        hsdevid=$(cat /sys/bus/usb/devices/1-1.4/idProduct)
        hsvenid=$(cat /sys/bus/usb/devices/1-1.4/idVendor)
        if [ "$hsdevid" = "0321" -a "$hsvenid" = "096e" ];then
            echo 2-1.2:1.0 > /sys//bus/usb/drivers/usb-storage/unbind
            insmod /lib/modules/4.14.22/HS_32EU.ko
        fi

	[ ! -f /etc/config/wireless ] && {
		# compat for brcm47xx and mvebu
		sleep 1
	}

	/bin/config_generate
	uci_apply_defaults
	
	# temporary hack until configd exists
	/sbin/reload_config
}
